### PR TITLE
Rank and honor: with Explanation

### PR DESCRIPTION
**Pull request by hobovsky**
Created as another take on #106. Still some things to do (verify links, navigation, sidebar), but please let me know how you like it.

Yay, got it working first time, and I am quite fond of the effect :)

~~However, I do not know what to do to have some kind of top level navigation from docs main page to https://deploy-preview-111--reverent-edison-2864ea.netlify.app/explanations/gamification/ - do we miss something on the main page, like an icon for "Explanations"/"About"?~~ - I think I got it, just tell me how you like it.

### CODE REVIEW

**Comment by Blind4Basics** [comment]
I begin to review the other PR... Should I review this one instead?

**Comment by hobovsky** [comment]
Both have the same content, this one has different (better IMO) organization, so yes, I'd say I prefer this one.

**Comment by Blind4Basics** [comment]
@kazk : lemme some time before you begin your review: I'll create another branch of this one with some significative changes, so if you wait, you'll only review the one that suits you the most.

**Comment by hobovsky** [comment]
Obsoleted by #112.

**Pull request closed without merging**
