### PR TITLE
Getting started: setting up

### PR DESCRIPTION
**Pull request by hobovsky**
#40 

Do I need to create a pull request if I consider the work not finished (i.e. not ready to be "pulled in"), but I want to get a review of some elements or ask for ideas?

I am interested if general form of this page is OK, or something is blatantly wrong.

### CODE REVIEW

**Comment by kazk** [comment]
> Do I need to create a pull request if I consider the work not finished (i.e. not ready to be "pulled in"), but I want to get a review of some elements or ask for ideas?

PRs are the easiest way to review and propose changes, so we should open one if you'd like to talk about something that's not in the repository yet.
You should be able to open a draft PR too. https://github.blog/2019-02-14-introducing-draft-pull-requests/

If you'd like to ask question about some code/doc in the repository, then just open an issue and paste the permalink of the lines. GitHub will show the code within the comment.

```
https://github.com/codewars/docs/blob/e05917d1ff79a207da2aaa0b651a8424ae67216e/package.json#L2
```
shows

https://github.com/codewars/docs/blob/e05917d1ff79a207da2aaa0b651a8424ae67216e/package.json#L2

**Comment by hobovsky** [comment]
Any idea why these changes do not appear in deployed docs? Docs are redeployed on merge to master, are they?

**Comment by kazk** [comment]
I'm not sure. Yeah, docs are deployed when merged to master. I'll try rebuilding it.

**Comment by kazk** [comment]
Looks like it failed because NPM was down. Cloudflare was down earlier and affected Codewars too.

**Comment by kazk** [comment]
Fixed

**Pull request merged**
