### PR TITLE
Fixing a link from Kata to Translations

### PR DESCRIPTION
**Pull request by gorohoroh**

### CODE REVIEW

**Comment by gorohoroh** [comment]
There was a check failure, and the error message is cryptic:

```
2021-01-14T11:21:21.3297473Z ##[group]Run actions/checkout@v2
2021-01-14T11:21:21.3298062Z with:
2021-01-14T11:21:21.3298483Z   ref: patch-1
2021-01-14T11:21:21.3298949Z   repository: codewars/docs
2021-01-14T11:21:21.3299418Z   ssh-strict: true
2021-01-14T11:21:21.3299940Z   persist-credentials: true
2021-01-14T11:21:21.3300584Z   clean: true
2021-01-14T11:21:21.3301008Z   fetch-depth: 1
2021-01-14T11:21:21.3301407Z   lfs: false
2021-01-14T11:21:21.3301816Z   submodules: false
2021-01-14T11:21:21.3302253Z ##[endgroup]
2021-01-14T11:21:21.7371034Z ##[error]Input required and not supplied: token
```

Not sure if this is actionable or related to my changes. I'd appreciate any advice.

**Comment by hobovsky** [comment]
I think it's because you are working with your fork of the repository. I do not know how github works in this aspect, and whether it's the fault of the setup of this particular repo, but you'd have to clone the codewars/docs repo directly and create a PR from this repo's branch, and not from your fork.

Thanks for contributing!

**Comment by gorohoroh** [comment]
@hobovsky Thanks, it looks like this has to do with [this GitHub problem](https://github.community/t/github-workflow-not-running-from-pull-request-from-forked-repository/16379/50), indeed.

I've enabled GitHub Actions in my fork, triggered a re-check, and it's still not working still. Let's close this PR then.

**Comment by hobovsky** [comment]
Does it work when you create a branch directly in codewars/docs repo and create a PR from such branch?

**Comment by gorohoroh** [comment]
@hobovsky It should work I believe, but I haven't really tried it. I was just trying to suggest a quick fix via the GitHub UI without cloning the entire thing, and it's not working, as we've seen. It's weird that the way GitHub implements Actions is basically blocking this kind of come-and-go fixes.

**Comment by hobovsky** [comment]
I see. Have you tried to introduce the change via GH web UI operating directly on codewars/docs code, for example editing it directly here: https://github.com/codewars/docs/blob/master/content/concepts/kata/index.md ?

I am not a day-to-day GitHub user so I am not sure if it would work, but when you commit a fix, it allows you to create a branch. I am just not sure in what repo. But it seems it worked for me.

image

**Comment by gorohoroh** [comment]
@hobovsky I don't have the option to edit and commit to a branch directly in codewars/docs. I believe this is because I have no permissions in this repo. When I try to edit a file in codewars/docs, GH only offers me to "Fork this project and edit a file".

**Comment by hobovsky** [comment]
I see, thanks for info. I was pretty sure that the repo is open for public access and contributions, but apparently it's not.

@kazk any insight on this, as well as on the OP's original problem?

**Comment by kazk** [comment]
> I see, thanks for info. I was pretty sure that the repo is open for public access and contributions, but apparently it's not.

It is, but this repository is only writable by us and pushing a branch here needs write access. On GitHub, you usually you work with other users' code by forking, creating a branch on your fork, then opening a PR like @gorohoroh did.

I originally assumed the Codewars community team will do that too, but it turned out you guys weren't familiar and preferred to work directly on this repository.

The current setup is optimized for you guys' workflow. For example, changes by the auto-formatter will push the changes for you. Unfortunately, that requires some setup that doesn't work when the change comes from a fork.

I'll make it conditional.

**Comment by hobovsky** [comment]
That's what you get for working with noobs :)

But then, when pushing from a fork, we won't get deployment previews, right? Actually this is the thing I would definitely miss.

**Comment by kazk** [comment]
Deployment preview should continue to work because it's by Netlify App hooked to PRs and not GitHub Actions.

**Comment by hobovsky** [comment]
Then, if pushing from fork and failed checks would not prevent the preview from appearing, it would be great.

**Comment by kazk** [comment]
I don't think it will prevent preview, but will prevent merge. https://github.com/codewars/docs/pull/238

**Pull request closed without merging**
